# WARNING: this file is auto-generated by 'build_sync_library.py'
# from the original file '__init__.py'
# DO NOT CHANGE! Change the original file instead.
"""File-tree based store for visual inspection and testing."""

from key_value.sync.code_gen.stores.filetree.store import FileTreeStore

__all__ = ["FileTreeStore"]
