# WARNING: this file is auto-generated by 'build_sync_library.py'
# from the original file 'test_opensearch.py'
# DO NOT CHANGE! Change the original file instead.
import contextlib
from collections.abc import Generator
from datetime import datetime, timedelta, timezone

import pytest
from dirty_equals import IsFloat
from inline_snapshot import snapshot
from key_value.shared.stores.wait import wait_for_true
from key_value.shared.utils.managed_entry import ManagedEntry
from opensearchpy import OpenSearch
from typing_extensions import override

from key_value.sync.code_gen.stores.base import BaseStore
from key_value.sync.code_gen.stores.opensearch import OpenSearchStore
from key_value.sync.code_gen.stores.opensearch.store import (
    OpenSearchSerializationAdapter,
    OpenSearchV1CollectionSanitizationStrategy,
    OpenSearchV1KeySanitizationStrategy,
)
from tests.code_gen.conftest import docker_container, should_skip_docker_tests
from tests.code_gen.stores.base import BaseStoreTests, ContextManagerStoreTestMixin

TEST_SIZE_LIMIT = 1 * 1024 * 1024  # 1MB
OS_HOST = "localhost"
OS_PORT = 9200
OS_URL = f"http://{OS_HOST}:{OS_PORT}"
OS_CONTAINER_PORT = 9200

WAIT_FOR_OPENSEARCH_TIMEOUT = 30
# Released 2023
# Recent stable version
OPENSEARCH_VERSIONS_TO_TEST = ["2.11.0", "2.18.0"]


def get_opensearch_client() -> OpenSearch:
    return OpenSearch(hosts=[OS_URL], use_ssl=False, verify_certs=False)


def ping_opensearch() -> bool:
    os_client: OpenSearch = get_opensearch_client()

    with os_client:
        try:
            return os_client.ping()
        except Exception:
            return False


def cleanup_opensearch_indices(opensearch_client: OpenSearch):
    with contextlib.suppress(Exception):
        indices = opensearch_client.indices.get(index="opensearch-kv-store-e2e-test-*")
        for index in indices:
            _ = opensearch_client.indices.delete(index=index)


class OpenSearchFailedToStartError(Exception):
    pass


def test_managed_entry_document_conversion():
    created_at = datetime(year=2025, month=1, day=1, hour=0, minute=0, second=0, tzinfo=timezone.utc)
    expires_at = created_at + timedelta(seconds=10)

    managed_entry = ManagedEntry(value={"test": "test"}, created_at=created_at, expires_at=expires_at)
    adapter = OpenSearchSerializationAdapter()
    document = adapter.dump_dict(entry=managed_entry)

    assert document == snapshot(
        {"value": {"flattened": {"test": "test"}}, "created_at": "2025-01-01T00:00:00+00:00", "expires_at": "2025-01-01T00:00:10+00:00"}
    )

    round_trip_managed_entry = adapter.load_dict(data=document)

    assert round_trip_managed_entry.value == managed_entry.value
    assert round_trip_managed_entry.created_at == created_at
    assert round_trip_managed_entry.ttl == IsFloat(lt=0)
    assert round_trip_managed_entry.expires_at == expires_at


@pytest.mark.skipif(should_skip_docker_tests(), reason="Docker is not available")
@pytest.mark.filterwarnings("ignore:A configured store is unstable and may change in a backwards incompatible way. Use at your own risk.")
class TestOpenSearchStore(ContextManagerStoreTestMixin, BaseStoreTests):
    @pytest.fixture(autouse=True, scope="session", params=OPENSEARCH_VERSIONS_TO_TEST)
    def setup_opensearch(self, request: pytest.FixtureRequest) -> Generator[None, None, None]:
        version = request.param
        os_image = f"opensearchproject/opensearch:{version}"

        with docker_container(
            f"opensearch-test-{version}",
            os_image,
            {str(OS_CONTAINER_PORT): OS_PORT},
            {"discovery.type": "single-node", "DISABLE_SECURITY_PLUGIN": "true", "OPENSEARCH_INITIAL_ADMIN_PASSWORD": "TestPassword123!"},
        ):
            if not wait_for_true(bool_fn=ping_opensearch, tries=WAIT_FOR_OPENSEARCH_TIMEOUT, wait_time=2):
                msg = f"OpenSearch {version} failed to start"
                raise OpenSearchFailedToStartError(msg)

            yield

    @pytest.fixture
    def opensearch_client(self, setup_opensearch: None) -> Generator[OpenSearch, None, None]:
        os_client = get_opensearch_client()

        with os_client:
            cleanup_opensearch_indices(opensearch_client=os_client)

            yield os_client

    @override
    @pytest.fixture
    def default_store(self, opensearch_client: OpenSearch) -> Generator[BaseStore, None, None]:
        store = OpenSearchStore(
            opensearch_client=opensearch_client, index_prefix="opensearch-kv-store-e2e-test", default_collection="test-collection"
        )

        with store:
            yield store

    @override
    @pytest.fixture
    def collection_sanitized_store(self, opensearch_client: OpenSearch) -> Generator[BaseStore, None, None]:
        store = OpenSearchStore(
            opensearch_client=opensearch_client,
            index_prefix="opensearch-kv-store-e2e-test",
            default_collection="test-collection",
            collection_sanitization_strategy=OpenSearchV1CollectionSanitizationStrategy(),
        )

        with store:
            yield store

    @override
    @pytest.fixture
    def key_sanitized_store(self, opensearch_client: OpenSearch) -> Generator[BaseStore, None, None]:
        store = OpenSearchStore(
            opensearch_client=opensearch_client,
            index_prefix="opensearch-kv-store-e2e-test",
            default_collection="test-collection",
            key_sanitization_strategy=OpenSearchV1KeySanitizationStrategy(),
        )

        with store:
            yield store

    @override
    @pytest.fixture
    def fully_sanitized_store(self, opensearch_client: OpenSearch) -> Generator[BaseStore, None, None]:
        store = OpenSearchStore(
            opensearch_client=opensearch_client,
            index_prefix="opensearch-kv-store-e2e-test",
            default_collection="test-collection",
            key_sanitization_strategy=OpenSearchV1KeySanitizationStrategy(),
            collection_sanitization_strategy=OpenSearchV1CollectionSanitizationStrategy(),
        )

        with store:
            yield store
