# WARNING: this file is auto-generated by 'build_sync_library.py'
# from the original file 'test_windows.py'
# DO NOT CHANGE! Change the original file instead.
import sys

import pytest
from typing_extensions import override

from key_value.sync.code_gen.stores.windows.store import WindowsStore
from tests.code_gen.stores.base import BaseStoreTests

# Skip all tests in this file if not on Windows
pytestmark = pytest.mark.skipif(sys.platform != "win32", reason="Windows-only tests")


class TestWindowsStore(BaseStoreTests):
    @override
    @pytest.fixture
    def store(self) -> WindowsStore:
        store = WindowsStore(service_name="py-key-value-test")
        # Clean up before test
        store.setup()
        store.destroy()
        yield store
        # Clean up after test
        store.destroy()
