# WARNING: this file is auto-generated by 'build_sync_library.py'
# from the original file '__init__.py'
# DO NOT CHANGE! Change the original file instead.
"""AWS S3-based key-value store."""

from key_value.sync.code_gen.stores.s3.store import S3Store

__all__ = ["S3Store"]
