# WARNING: this file is auto-generated by 'build_sync_library.py'
# from the original file 'store.py'
# DO NOT CHANGE! Change the original file instead.
from key_value.sync.code_gen.errors.base import BaseKeyValueError


class KeyValueStoreError(BaseKeyValueError):
    """Base exception for all Key-Value store errors."""


class StoreSetupError(KeyValueStoreError):
    """Raised when a store setup fails."""


class StoreConnectionError(KeyValueStoreError):
    """Raised when unable to connect to or communicate with the underlying store."""
