# WARNING: this file is auto-generated by 'build_sync_library.py'
# from the original file 'base.py'
# DO NOT CHANGE! Change the original file instead.
from collections.abc import Sequence
from typing import Any, SupportsFloat

from typing_extensions import override

from key_value.sync.code_gen.protocols.key_value import KeyValue


class BaseWrapper(KeyValue):
    """A base wrapper for KVStore implementations that passes through to the underlying store."""

    key_value: KeyValue

    @override
    def get(self, key: str, *, collection: str | None = None) -> dict[str, Any] | None:
        return self.key_value.get(collection=collection, key=key)

    @override
    def get_many(self, keys: list[str], *, collection: str | None = None) -> list[dict[str, Any] | None]:
        return self.key_value.get_many(collection=collection, keys=keys)

    @override
    def ttl(self, key: str, *, collection: str | None = None) -> tuple[dict[str, Any] | None, float | None]:
        return self.key_value.ttl(collection=collection, key=key)

    @override
    def ttl_many(self, keys: list[str], *, collection: str | None = None) -> list[tuple[dict[str, Any] | None, float | None]]:
        return self.key_value.ttl_many(collection=collection, keys=keys)

    @override
    def put(self, key: str, value: dict[str, Any], *, collection: str | None = None, ttl: SupportsFloat | None = None) -> None:
        return self.key_value.put(collection=collection, key=key, value=value, ttl=ttl)

    @override
    def put_many(
        self,
        keys: list[str],
        values: Sequence[dict[str, Any]],
        *,
        collection: str | None = None,
        ttl: Sequence[SupportsFloat | None] | SupportsFloat | None = None,
    ) -> None:
        return self.key_value.put_many(keys=keys, values=values, collection=collection, ttl=ttl)

    @override
    def delete(self, key: str, *, collection: str | None = None) -> bool:
        return self.key_value.delete(collection=collection, key=key)

    @override
    def delete_many(self, keys: list[str], *, collection: str | None = None) -> int:
        return self.key_value.delete_many(keys=keys, collection=collection)
