# WARNING: this file is auto-generated by 'build_sync_library.py'
# from the original file 'test_store.py'
# DO NOT CHANGE! Change the original file instead.
import pytest
from typing_extensions import override

from key_value.sync.code_gen.stores.simple.store import SimpleStore
from tests.code_gen.stores.conftest import BaseStoreTests


class TestSimpleStore(BaseStoreTests):
    @override
    @pytest.fixture
    def store(self) -> SimpleStore:
        return SimpleStore(max_entries=500)
