# WARNING: this file is auto-generated by 'build_sync_library.py'
# from the original file 'wrapper.py'
# DO NOT CHANGE! Change the original file instead.
from collections.abc import Sequence
from typing import Any

from typing_extensions import override

from key_value.sync.code_gen.protocols.key_value import KeyValue
from key_value.sync.code_gen.utils.compound import prefix_key, unprefix_key
from key_value.sync.code_gen.wrappers.base import BaseWrapper


class PrefixKeysWrapper(BaseWrapper):
    """A wrapper that prefixes key names before delegating to the underlying store."""

    def __init__(self, store: KeyValue, prefix: str) -> None:
        """Initialize the prefix keys wrapper.

        Args:
            store: The store to wrap.
            prefix: The prefix to add to the keys.
        """
        self.store: KeyValue = store
        self.prefix: str = prefix
        super().__init__()

    def _prefix_key(self, key: str) -> str:
        return prefix_key(prefix=self.prefix, key=key)

    def _unprefix_key(self, key: str) -> str:
        return unprefix_key(prefix=self.prefix, key=key)

    @override
    def get(self, key: str, *, collection: str | None = None) -> dict[str, Any] | None:
        new_key: str = self._prefix_key(key=key)
        return self.store.get(key=new_key, collection=collection)

    @override
    def get_many(self, keys: Sequence[str], *, collection: str | None = None) -> list[dict[str, Any] | None]:
        new_keys: list[str] = [self._prefix_key(key=key) for key in keys]
        return self.store.get_many(keys=new_keys, collection=collection)

    @override
    def ttl(self, key: str, *, collection: str | None = None) -> tuple[dict[str, Any] | None, float | None]:
        new_key: str = self._prefix_key(key=key)
        return self.store.ttl(key=new_key, collection=collection)

    @override
    def ttl_many(self, keys: Sequence[str], *, collection: str | None = None) -> list[tuple[dict[str, Any] | None, float | None]]:
        new_keys: list[str] = [self._prefix_key(key=key) for key in keys]
        return self.store.ttl_many(keys=new_keys, collection=collection)

    @override
    def put(self, key: str, value: dict[str, Any], *, collection: str | None = None, ttl: float | None = None) -> None:
        new_key: str = self._prefix_key(key=key)
        return self.store.put(key=new_key, value=value, collection=collection, ttl=ttl)

    @override
    def put_many(
        self,
        keys: Sequence[str],
        values: Sequence[dict[str, Any]],
        *,
        collection: str | None = None,
        ttl: Sequence[float | None] | float | None = None,
    ) -> None:
        new_keys: list[str] = [self._prefix_key(key=key) for key in keys]
        return self.store.put_many(keys=new_keys, values=values, collection=collection, ttl=ttl)

    @override
    def delete(self, key: str, *, collection: str | None = None) -> bool:
        new_key: str = self._prefix_key(key=key)
        return self.store.delete(key=new_key, collection=collection)

    @override
    def delete_many(self, keys: Sequence[str], *, collection: str | None = None) -> int:
        new_keys: list[str] = [self._prefix_key(key=key) for key in keys]
        return self.store.delete_many(keys=new_keys, collection=collection)
