# WARNING: this file is auto-generated by 'build_sync_library.py'
# from the original file 'test.py'
# DO NOT CHANGE! Change the original file instead.
import os

from cryptography.fernet import Fernet
from key_value.sync.code_gen.stores.dynamodb.store import DynamoDBStore

from key_value.sync.code_gen.wrappers.encryption.fernet import FernetEncryptionWrapper

PERSISTENCE_TABLE_NAME = os.getenv("PERSISTENCE_TABLE_NAME", "test-key-value")
STORAGE_ENCRYPTION_KEY = os.getenv("STORAGE_ENCRYPTION_KEY")

wrapped_client_storage: DynamoDBStore

client_storage = DynamoDBStore(table_name=PERSISTENCE_TABLE_NAME)
if STORAGE_ENCRYPTION_KEY:
    wrapped_client_storage = FernetEncryptionWrapper(key_value=client_storage, fernet=Fernet(STORAGE_ENCRYPTION_KEY))
