# WARNING: this file is auto-generated by 'build_sync_library.py'
# from the original file 'wrapper.py'
# DO NOT CHANGE! Change the original file instead.
from collections.abc import Mapping, Sequence
from typing import Any, SupportsFloat

from pydantic import TypeAdapter
from typing_extensions import override

from key_value.sync.code_gen.protocols.key_value import KeyValue
from key_value.sync.code_gen.wrappers.base import BaseWrapper


class PydanticJsonWrapper(BaseWrapper):
    """A wrapper that ensures all values are JSON-serializable using Pydantic's TypeAdapter.

    This wrapper automatically converts values to JSON-safe formats before storage,
    ensuring compatibility with stores that require JSON-serializable data.
    """

    _key_value: KeyValue
    key_value: KeyValue  # Alias for BaseWrapper compatibility

    def __init__(self, key_value: KeyValue) -> None:
        """Initialize the PydanticJsonWrapper.

        Args:
            key_value: The underlying key-value store to wrap.
        """
        self._key_value = key_value
        self.key_value = key_value  # Alias for BaseWrapper compatibility
        self._adapter: TypeAdapter[dict[str, Any]] = TypeAdapter(dict[str, Any])

    def _to_json_safe(self, value: Mapping[str, Any]) -> dict[str, Any]:
        """Convert a value to a JSON-safe format using Pydantic.

        Args:
            value: The value to convert.

        Returns:
            A JSON-safe dictionary.
        """
        return self._adapter.dump_python(value, mode="json")  # type: ignore[return-value]

    @override
    def put(self, key: str, value: Mapping[str, Any], *, collection: str | None = None, ttl: SupportsFloat | None = None) -> None:
        """Store a value after converting it to JSON-safe format.

        Args:
            key: The key to store.
            value: The value to store (will be converted to JSON-safe format).
            collection: The collection to use.
            ttl: The time-to-live in seconds.
        """
        json_safe_value = self._to_json_safe(value)
        self._key_value.put(key=key, value=json_safe_value, collection=collection, ttl=ttl)

    @override
    def put_many(
        self, keys: Sequence[str], values: Sequence[Mapping[str, Any]], *, collection: str | None = None, ttl: SupportsFloat | None = None
    ) -> None:
        """Store multiple values after converting them to JSON-safe format.

        Args:
            keys: The keys to store.
            values: The values to store (will be converted to JSON-safe format).
            collection: The collection to use.
            ttl: The time-to-live in seconds for all items.
        """
        json_safe_values = [self._to_json_safe(value) for value in values]
        self._key_value.put_many(keys=keys, values=json_safe_values, collection=collection, ttl=ttl)
