# WARNING: this file is auto-generated by 'build_sync_library.py'
# from the original file '__init__.py'
# DO NOT CHANGE! Change the original file instead.
"""Firestore key-value store."""

from key_value.sync.code_gen.stores.firestore.store import FirestoreStore

__all__ = ["FirestoreStore"]
