# WARNING: this file is auto-generated by 'build_sync_library.py'
# from the original file 'test_windows_registry.py'
# DO NOT CHANGE! Change the original file instead.
from typing import TYPE_CHECKING, Any

import pytest
from key_value.shared_test.cases import LARGE_TEST_DATA_ARGNAMES, LARGE_TEST_DATA_ARGVALUES, LARGE_TEST_DATA_IDS
from typing_extensions import override

from key_value.sync.code_gen.stores.base import BaseStore
from tests.code_gen.conftest import detect_on_windows
from tests.code_gen.stores.base import BaseStoreTests

if TYPE_CHECKING:
    from key_value.sync.code_gen.stores.windows_registry.store import WindowsRegistryStore


@pytest.mark.skipif(condition=not detect_on_windows(), reason="WindowsRegistryStore is only available on Windows")
class TestWindowsRegistryStore(BaseStoreTests):
    @override
    @pytest.fixture
    def store(self) -> "WindowsRegistryStore":
        # Use a test-specific root to avoid conflicts
        from key_value.sync.code_gen.stores.windows_registry.store import WindowsRegistryStore

        store = WindowsRegistryStore(root="py-key-value-test")
        store.delete_many(collection="test", keys=["test"])
        store.delete_many(collection="test_collection", keys=["test_key"])

        return store

    @override
    @pytest.mark.skip(reason="We do not test boundedness of registry stores")
    def test_not_unbounded(self, store: BaseStore): ...

    @override
    @pytest.mark.parametrize(argnames=LARGE_TEST_DATA_ARGNAMES, argvalues=LARGE_TEST_DATA_ARGVALUES, ids=LARGE_TEST_DATA_IDS)
    def test_get_large_put_get(self, store: BaseStore, data: dict[str, Any], json: str):
        store.put(collection="test", key="test", value=data)
        assert store.get(collection="test", key="test") == data
