# WARNING: this file is auto-generated by 'build_sync_library.py'
# from the original file '__init__.py'
# DO NOT CHANGE! Change the original file instead.
"""Sanitization migration wrapper for gradual strategy transitions.

This module provides a wrapper that enables gradual migration between different
sanitization strategies without breaking access to existing data.
"""

from key_value.sync.code_gen.wrappers.sanitization_migration.wrapper import SanitizationMigrationWrapper

__all__ = ["SanitizationMigrationWrapper"]
