# WARNING: this file is auto-generated by 'build_sync_library.py'
# from the original file 'test_keyring.py'
# DO NOT CHANGE! Change the original file instead.
import pytest
from typing_extensions import override

from key_value.sync.code_gen.stores.base import BaseStore
from key_value.sync.code_gen.stores.keyring.store import KeyringStore
from tests.code_gen.stores.base import BaseStoreTests


class TestKeychainStore(BaseStoreTests):
    @override
    @pytest.fixture
    def store(self) -> KeyringStore:
        # Use a test-specific service name to avoid conflicts
        store = KeyringStore(service_name="py-key-value-test")
        store.delete_many(collection="test", keys=["test"])
        store.delete_many(collection="test_collection", keys=["test_key"])

        return store

    @override
    @pytest.mark.skip(reason="We do not test boundedness of keyring stores")
    def test_not_unbounded(self, store: BaseStore): ...
