# WARNING: this file is auto-generated by 'build_sync_library.py'
# from the original file 'store.py'
# DO NOT CHANGE! Change the original file instead.
from key_value.shared.utils.managed_entry import ManagedEntry
from typing_extensions import override

from key_value.sync.code_gen.stores.base import BaseStore


class NullStore(BaseStore):
    """Null object pattern store that accepts all operations but stores nothing."""

    @override
    def _get_managed_entry(self, *, key: str, collection: str) -> ManagedEntry | None:
        return None

    @override
    def _put_managed_entry(self, *, key: str, collection: str, managed_entry: ManagedEntry) -> None:
        pass

    @override
    def _delete_managed_entry(self, *, key: str, collection: str) -> bool:
        return False
