# WARNING: this file is auto-generated by 'build_sync_library.py'
# from the original file 'test_prefix_key.py'
# DO NOT CHANGE! Change the original file instead.
import pytest
from typing_extensions import override

from key_value.sync.code_gen.stores.memory.store import MemoryStore
from key_value.sync.code_gen.wrappers.prefix_keys import PrefixKeysWrapper
from tests.code_gen.stores.base import BaseStoreTests


class TestPrefixKeyWrapper(BaseStoreTests):
    @override
    @pytest.fixture
    def store(self, memory_store: MemoryStore) -> PrefixKeysWrapper:
        return PrefixKeysWrapper(key_value=memory_store, prefix="key_prefix")
