# WARNING: this file is auto-generated by 'build_sync_library.py'
# from the original file 'test_statistics.py'
# DO NOT CHANGE! Change the original file instead.
import pytest
from typing_extensions import override

from key_value.sync.code_gen.stores.memory.store import MemoryStore
from key_value.sync.code_gen.wrappers.statistics import StatisticsWrapper
from tests.code_gen.stores.base import BaseStoreTests


class TestStatisticsWrapper(BaseStoreTests):

    @override
    @pytest.fixture
    def store(self, memory_store: MemoryStore) -> StatisticsWrapper:
        return StatisticsWrapper(key_value=memory_store)
