# WARNING: this file is auto-generated by 'build_sync_library.py'
# from the original file 'test_prefix_collection.py'
# DO NOT CHANGE! Change the original file instead.
import pytest
from typing_extensions import override

from key_value.sync.code_gen.stores.memory.store import MemoryStore
from key_value.sync.code_gen.wrappers.prefix_collections import PrefixCollectionsWrapper
from tests.code_gen.stores.base import BaseStoreTests


class TestPrefixCollectionWrapper(BaseStoreTests):
    @override
    @pytest.fixture
    def store(self, memory_store: MemoryStore) -> PrefixCollectionsWrapper:
        return PrefixCollectionsWrapper(key_value=memory_store, prefix="collection_prefix")
