# WARNING: this file is auto-generated by 'build_sync_library.py'
# from the original file 'test_clamp_ttl.py'
# DO NOT CHANGE! Change the original file instead.
import pytest
from dirty_equals import IsFloat
from typing_extensions import override

from key_value.sync.code_gen.stores.memory.store import MemoryStore
from key_value.sync.code_gen.wrappers.ttl_clamp import TTLClampWrapper
from tests.code_gen.stores.base import BaseStoreTests


class TestTTLClampWrapper(BaseStoreTests):
    @override
    @pytest.fixture
    def store(self, memory_store: MemoryStore) -> TTLClampWrapper:
        return TTLClampWrapper(store=memory_store, min_ttl=0, max_ttl=100)

    def test_put_below_min_ttl(self, memory_store: MemoryStore):
        ttl_clamp_store: TTLClampWrapper = TTLClampWrapper(store=memory_store, min_ttl=50, max_ttl=100)

        ttl_clamp_store.put(collection="test", key="test", value={"test": "test"}, ttl=5)
        assert ttl_clamp_store.get(collection="test", key="test") is not None

        (value, ttl) = ttl_clamp_store.ttl(collection="test", key="test")
        assert value is not None
        assert ttl is not None
        assert ttl == IsFloat(approx=50)

    def test_put_above_max_ttl(self, memory_store: MemoryStore):
        ttl_clamp_store: TTLClampWrapper = TTLClampWrapper(store=memory_store, min_ttl=0, max_ttl=100)

        ttl_clamp_store.put(collection="test", key="test", value={"test": "test"}, ttl=1000)
        assert ttl_clamp_store.get(collection="test", key="test") is not None

        (value, ttl) = ttl_clamp_store.ttl(collection="test", key="test")
        assert value is not None
        assert ttl is not None
        assert ttl == IsFloat(approx=100)

    def test_put_missing_ttl(self, memory_store: MemoryStore):
        ttl_clamp_store: TTLClampWrapper = TTLClampWrapper(store=memory_store, min_ttl=0, max_ttl=100, missing_ttl=50)

        ttl_clamp_store.put(collection="test", key="test", value={"test": "test"}, ttl=None)
        assert ttl_clamp_store.get(collection="test", key="test") is not None

        (value, ttl) = ttl_clamp_store.ttl(collection="test", key="test")
        assert value is not None
        assert ttl is not None

        assert ttl == IsFloat(approx=50)
