# WARNING: this file is auto-generated by 'build_sync_library.py'
# from the original file 'test_memory.py'
# DO NOT CHANGE! Change the original file instead.
import pytest
from typing_extensions import override

from key_value.sync.code_gen.stores.memory.store import MemoryStore
from tests.code_gen.stores.conftest import BaseStoreTests


class TestMemoryStore(BaseStoreTests):
    @override
    @pytest.fixture
    def store(self) -> MemoryStore:
        return MemoryStore(max_entries_per_collection=500)
