# WARNING: this file is auto-generated by 'build_sync_library.py'
# from the original file '__init__.py'
# DO NOT CHANGE! Change the original file instead.
from key_value.sync.code_gen.stores.rocksdb.store import RocksDBStore

__all__ = ["RocksDBStore"]
