# WARNING: this file is auto-generated by 'build_sync_library.py'
# from the original file 'test_disk.py'
# DO NOT CHANGE! Change the original file instead.
import tempfile
from collections.abc import Generator

import pytest
from typing_extensions import override

from key_value.sync.code_gen.stores.disk import DiskStore
from tests.code_gen.stores.base import BaseStoreTests, ContextManagerStoreTestMixin

TEST_SIZE_LIMIT = 100 * 1024  # 100KB


class TestDiskStore(ContextManagerStoreTestMixin, BaseStoreTests):
    @override
    @pytest.fixture
    def store(self) -> Generator[DiskStore, None, None]:
        with tempfile.TemporaryDirectory() as temp_dir:
            yield DiskStore(directory=temp_dir, max_size=TEST_SIZE_LIMIT)
