# WARNING: this file is auto-generated by 'build_sync_library.py'
# from the original file 'test_multi_disk.py'
# DO NOT CHANGE! Change the original file instead.
import tempfile
from collections.abc import Generator
from pathlib import Path

import pytest
from typing_extensions import override

from key_value.sync.code_gen.stores.disk.multi_store import MultiDiskStore
from tests.code_gen.stores.base import BaseStoreTests, ContextManagerStoreTestMixin

TEST_SIZE_LIMIT = 100 * 1024  # 100KB


class TestMultiDiskStore(ContextManagerStoreTestMixin, BaseStoreTests):
    @pytest.fixture(scope="session")
    def multi_disk_store(self) -> Generator[MultiDiskStore, None, None]:
        with tempfile.TemporaryDirectory() as temp_dir:
            yield MultiDiskStore(base_directory=Path(temp_dir), max_size=TEST_SIZE_LIMIT)

    @override
    @pytest.fixture
    def store(self, multi_disk_store: MultiDiskStore) -> MultiDiskStore:
        for collection in multi_disk_store._cache:  # pyright: ignore[reportPrivateUsage]
            multi_disk_store._cache[collection].clear()  # pyright: ignore[reportPrivateUsage]

        return multi_disk_store
