# WARNING: this file is auto-generated by 'build_sync_library.py'
# from the original file '__init__.py'
# DO NOT CHANGE! Change the original file instead.
"""Migration wrapper for gradual store transitions.

This module provides a wrapper that enables gradual migration between two stores
(e.g., stores with different configurations) without breaking access to existing data.
"""

from key_value.sync.code_gen.wrappers.migration.wrapper import MigrationWrapper

__all__ = ["MigrationWrapper"]
