# WARNING: this file is auto-generated by 'build_sync_library.py'
# from the original file '__init__.py'
# DO NOT CHANGE! Change the original file instead.
"""Pydantic JSON wrapper for ensuring JSON-serializable value storage."""

from key_value.sync.code_gen.wrappers.pydantic_json.wrapper import PydanticJsonWrapper

__all__ = ["PydanticJsonWrapper"]
